name: NanoTabPFN
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _python_abi3_support=1.0
  - aom=3.12.1
  - asttokens=3.0.1
  - blas=1.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.12.12
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - khronos-opencl-icd-loader=2025.07.22
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libsodium=1.0.20
  - libtiff=4.7.1
  - libuv=1.48.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.5
  - numpy=2.3.1
  - numpy-base=2.3.1
  - opencl-headers=2025.07.22
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - requests=2.32.5
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - backoff==2.2.1
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - distro==1.9.0
      - einops==0.8.1
      - eval-type-backport==0.3.0
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.6
      - joblib==1.5.2
      - kditransform==1.2.0
      - kiwisolver==1.4.9
      - liac-arff==2.5.0
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - minio==7.2.20
      - numba==0.62.1
      - openml==0.15.1
      - pandas==2.3.3
      - posthog==6.9.3
      - pyarrow==22.0.0
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - schedulefree==1.4.1
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - shellingham==1.5.4
      - sympy==1.13.1
      - tabpfn==6.0.6
      - tabpfn-common-utils==0.2.10
      - threadpoolctl==3.6.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - xmltodict==1.0.2
prefix: C:\Users\gregg\miniconda3\envs\NanoTabPFN
